//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YearEndCalculation.WindowsFormUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class LicenceSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static LicenceSetting defaultInstance = ((LicenceSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LicenceSetting())));
        
        public static LicenceSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLicensed {
            get {
                return ((bool)(this["IsLicensed"]));
            }
            set {
                this["IsLicensed"] = value;
            }
        }
    }
}
